package advent.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF4E6629)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCFEDA1)
val onPrimaryContainerLight = Color(0xFF374E14)
val secondaryLight = Color(0xFF755B0B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDF94)
val onSecondaryContainerLight = Color(0xFF594400)
val tertiaryLight = Color(0xFF006A64)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9DF2E9)
val onTertiaryContainerLight = Color(0xFF00504B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAFAEE)
val onBackgroundLight = Color(0xFF1A1C16)
val surfaceLight = Color(0xFFF9FAEF)
val onSurfaceLight = Color(0xFF1A1C16)
val surfaceVariantLight = Color(0xFFE1E4D5)
val onSurfaceVariantLight = Color(0xFF45483D)
val outlineLight = Color(0xFF75796C)
val outlineVariantLight = Color(0xFFC5C8B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F312A)
val inverseOnSurfaceLight = Color(0xFFF0F2E6)
val inversePrimaryLight = Color(0xFFB4D088)
val surfaceDimLight = Color(0xFFD9DBD0)
val surfaceBrightLight = Color(0xFFF9FAEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F5E9)
val surfaceContainerLight = Color(0xFFEDEFE4)
val surfaceContainerHighLight = Color(0xFFE8E9DE)
val surfaceContainerHighestLight = Color(0xFFE2E3D8)

val primaryLightMediumContrast = Color(0xFF273C03)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF5C7537)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF453400)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF85691C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003E3A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF197A73)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAFAEE)
val onBackgroundLightMediumContrast = Color(0xFF1A1C16)
val surfaceLightMediumContrast = Color(0xFFF9FAEF)
val onSurfaceLightMediumContrast = Color(0xFF0F120C)
val surfaceVariantLightMediumContrast = Color(0xFFE1E4D5)
val onSurfaceVariantLightMediumContrast = Color(0xFF34372D)
val outlineLightMediumContrast = Color(0xFF505448)
val outlineVariantLightMediumContrast = Color(0xFF6B6E62)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F312A)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F2E6)
val inversePrimaryLightMediumContrast = Color(0xFFB4D088)
val surfaceDimLightMediumContrast = Color(0xFFC6C7BD)
val surfaceBrightLightMediumContrast = Color(0xFFF9FAEF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F5E9)
val surfaceContainerLightMediumContrast = Color(0xFFE8E9DE)
val surfaceContainerHighLightMediumContrast = Color(0xFFDCDED3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D3C8)

val primaryLightHighContrast = Color(0xFF1E3200)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF395016)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF392A00)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5C4600)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00322F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00534E)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAFAEE)
val onBackgroundLightHighContrast = Color(0xFF1A1C16)
val surfaceLightHighContrast = Color(0xFFF9FAEF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE1E4D5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2A2D23)
val outlineVariantLightHighContrast = Color(0xFF474B3F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F312A)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB4D088)
val surfaceDimLightHighContrast = Color(0xFFB8BAAF)
val surfaceBrightLightHighContrast = Color(0xFFF9FAEF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F2E6)
val surfaceContainerLightHighContrast = Color(0xFFE2E3D8)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D5CB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C7BD)

val primaryDark = Color(0xFFB4D088)
val onPrimaryDark = Color(0xFF213600)
val primaryContainerDark = Color(0xFF374E14)
val onPrimaryContainerDark = Color(0xFFCFEDA1)
val secondaryDark = Color(0xFFE5C36C)
val onSecondaryDark = Color(0xFF3E2E00)
val secondaryContainerDark = Color(0xFF594400)
val onSecondaryContainerDark = Color(0xFFFFDF94)
val tertiaryDark = Color(0xFF81D5CD)
val onTertiaryDark = Color(0xFF003734)
val tertiaryContainerDark = Color(0xFF00504B)
val onTertiaryContainerDark = Color(0xFF9DF2E9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFE2E3D8)
val surfaceVariantDark = Color(0xFF45483D)
val onSurfaceVariantDark = Color(0xFFC5C8B9)
val outlineDark = Color(0xFF8F9285)
val outlineVariantDark = Color(0xFF45483D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3D8)
val inverseOnSurfaceDark = Color(0xFF2F312A)
val inversePrimaryDark = Color(0xFF4E6629)
val surfaceDimDark = Color(0xFF12140E)
val surfaceBrightDark = Color(0xFF373A33)
val surfaceContainerLowestDark = Color(0xFF0C0F09)
val surfaceContainerLowDark = Color(0xFF1A1C16)
val surfaceContainerDark = Color(0xFF1E211A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF33362E)

val primaryDarkMediumContrast = Color(0xFFC9E69C)
val onPrimaryDarkMediumContrast = Color(0xFF192A00)
val primaryContainerDarkMediumContrast = Color(0xFF7F9957)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFDD87F)
val onSecondaryDarkMediumContrast = Color(0xFF312400)
val secondaryContainerDarkMediumContrast = Color(0xFFAC8D3D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF97EBE3)
val onTertiaryDarkMediumContrast = Color(0xFF002B28)
val tertiaryContainerDarkMediumContrast = Color(0xFF489E97)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF12140E)
val onBackgroundDarkMediumContrast = Color(0xFFE2E3D8)
val surfaceDarkMediumContrast = Color(0xFF12140E)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF45483D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDBDECF)
val outlineDarkMediumContrast = Color(0xFFB0B3A5)
val outlineVariantDarkMediumContrast = Color(0xFF8E9284)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E3D8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B24)
val inversePrimaryDarkMediumContrast = Color(0xFF384F15)
val surfaceDimDarkMediumContrast = Color(0xFF12140E)
val surfaceBrightDarkMediumContrast = Color(0xFF43453E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF060804)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1F18)
val surfaceContainerDarkMediumContrast = Color(0xFF262922)
val surfaceContainerHighDarkMediumContrast = Color(0xFF31342C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3F37)

val primaryDarkHighContrast = Color(0xFFDDFAAE)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB0CC84)
val onPrimaryContainerDarkHighContrast = Color(0xFF060E00)
val secondaryDarkHighContrast = Color(0xFFFFEECD)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE1BF69)
val onSecondaryContainerDarkHighContrast = Color(0xFF110A00)
val tertiaryDarkHighContrast = Color(0xFFACFFF7)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF7DD1C9)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E0D)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF12140E)
val onBackgroundDarkHighContrast = Color(0xFFE2E3D8)
val surfaceDarkHighContrast = Color(0xFF12140E)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF45483D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEFF1E2)
val outlineVariantDarkHighContrast = Color(0xFFC1C4B6)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E3D8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF384F15)
val surfaceDimDarkHighContrast = Color(0xFF12140E)
val surfaceBrightDarkHighContrast = Color(0xFF4E5149)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E211A)
val surfaceContainerDarkHighContrast = Color(0xFF2F312A)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A3C35)
val surfaceContainerHighestDarkHighContrast = Color(0xFF454840)

val ColorScheme.isDark: Boolean
    @Composable
    get() = surface.red * 0.2126 + surface.green * 0.7152 + surface.blue * 0.0722 <= 0.5f

@Composable
fun ColorScheme.consoleContainer() = if (isDark) consoleContainerDark else consoleContainerLight

@Composable
fun ColorScheme.console() = if (isDark) consoleDark else consoleLight

@Composable
fun ColorScheme.onConsole() = if (isDark) onConsoleDark else onConsoleLight

@Composable
fun ColorScheme.onConsoleContainer() =
    if (isDark) onConsoleContainerDark else onConsoleContainerLight


val consoleLight = Color(0xFF505B92)
val onConsoleLight = Color(0xFFFFFFFF)
val consoleContainerLight = Color(0xFFDEE1FF)
val onConsoleContainerLight = Color(0xFF384379)

val consoleLightMediumContrast = Color(0xFF273267)
val onConsoleLightMediumContrast = Color(0xFFFFFFFF)
val consoleContainerLightMediumContrast = Color(0xFF5F6AA2)
val onConsoleContainerLightMediumContrast = Color(0xFFFFFFFF)

val consoleLightHighContrast = Color(0xFF1D285C)
val onConsoleLightHighContrast = Color(0xFFFFFFFF)
val consoleContainerLightHighContrast = Color(0xFF3B457B)
val onConsoleContainerLightHighContrast = Color(0xFFFFFFFF)

val consoleDark = Color(0xFFB9C3FF)
val onConsoleDark = Color(0xFF212C61)
val consoleContainerDark = Color(0xFF384379)
val onConsoleContainerDark = Color(0xFFDEE1FF)

val consoleDarkMediumContrast = Color(0xFFD6DAFF)
val onConsoleDarkMediumContrast = Color(0xFF152155)
val consoleContainerDarkMediumContrast = Color(0xFF838DC8)
val onConsoleContainerDarkMediumContrast = Color(0xFF000000)

val consoleDarkHighContrast = Color(0xFFEFEFFF)
val onConsoleDarkHighContrast = Color(0xFF000000)
val consoleContainerDarkHighContrast = Color(0xFFB5BFFD)
val onConsoleContainerDarkHighContrast = Color(0xFF000630)
